trigger: none

pr: none

schedules:
- cron: "0 20 * * *"
  displayName: "Daily 8pm build"
  branches:
    include:
    - master
  always: true

jobs:
- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: checked
    platforms:
    - Linux_x64
    - Windows_NT_x64

- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: test-job.yml
    buildConfig: checked
    platforms:
    - Linux_x64
    - Windows_NT_x64
    helixQueueGroup: ci
    jobParameters:
      testGroup: jitstressregs
      corefxTests: true
      displayNameArgs: CoreFX