trigger: none

pr: none

schedule:
- cron: '0 20 * * *'
  displayName: 'coreclr-jitstress 8pm daily build'
  branches:
    include:
    - master
  always: true

jobs:
- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: checked
    platformGroup: all

- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: test-job.yml
    buildConfig: checked
    platformGroup: all
    helixQueueGroup: ci
