trigger: none

pr: none

schedules:
- cron: "0 20 * * *"
  displayName: "Daily 8pm build"
  branches:
    include:
    - master
  always: true

jobs:
- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: checked
    platformGroup: all

- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: test-job.yml
    buildConfig: checked
    platformGroup: all
    helixQueueGroup: ci
    jobParameters:
      testGroup: jitstress
