trigger: none

pr: none

jobs:
- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: checked
    platformGroup: gcstress

- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: test-job.yml
    buildConfig: checked
    platformGroup: gcstress
    helixQueueGroup: ci
    jobParameters:
      testGroup: r2r-extra
      readyToRun: true
      displayNameArgs: R2R
